//==============================================================
//========================== WARNING ===========================
//==============================================================
//= Do not edit this file if you don't know what you're doing! =
//==============================================================

//Array randomizer (Durstenfeld shuffle)
function shuffle(array) {
	for (var i = array.length - 1; i > 0; i--) {
			var j = Math.floor(Math.random() * (i + 1));
			var temp = array[i];
			array[i] = array[j];
			array[j] = temp;
	}
}

// Delay between message changes
// in milliseconds
var messagesDelay = 5000;

// Messages fade time
// in milliseconds
var messagesFade = 1000;

var messages = [
	"Join our discord: discord.gg/npc"
	/*
	"The server overhaul is done! Expect more new content and improvements to the server.",
	"Join our discord: nzvp.net/discord",
	"Seeing errors? nzvp.net/sbox-workshop",
	"Enjoy your time on our server!",
	"Join our steam group: nzvp.net/group",
	"We add new addons every month. Suggest some on our discord!"
	*/
];

var neededFiles;
var downloadedFiles = 0;

function DownloadingFile( fileName ) {
	downloadedFiles++;
	refreshProgress();

	setStatus("Downloading files...");
}

function SetStatusChanged( status ) {
	if (status.indexOf("Getting Addon #") != -1) {
		downloadedFiles++;
		refreshProgress();
	}else if (status == "Sending client info...") {
		setProgress(100);
	}

	setStatus(status);
}

/* Useless...
function SetFilesTotal( total ) {
	console.log("SetFilesTotal("+total+")");
}*/

function SetFilesNeeded( needed ) {
	neededFiles = needed + 1;
}

function refreshProgress() {
	var progress = Math.floor(((downloadedFiles / neededFiles)*100));

	setProgress(progress);
}

function setStatus(text) {
	$("#status").html(text);
}
function setProgress(progress) {
	$("#loading-progress").css("width", progress + "%");
}

function showMessage(message) {
	if (message >= messages.length)
		message = 0;

  $("#messages").html(messages[message]);

	if (messages.length > 1) {
		setTimeout(function() {
			showMessage(message+1);
		}, messagesDelay + messagesFade*2);
	}
}

var video = document.querySelector('video');
video.addEventListener('play', () => {
	console.log("Video playing");
	$("html").css("background-color", "transparent");
	shuffle(messages);
	showMessage(0);

	$("#header").css("text-align", "center");
});
